name: nitsan/ns-headline
typeName: nitsan_nsheadline
group: t3themeagency_content_blocks
prefixFields: false
prefixType: vendor
fields:
  -
    identifier: title
    label: 'LLL:EXT:ns_theme_agency/Resources/Private/Language/locallang_flex.xlf:general.title'
    type: Text
    required: true
  -
    identifier: subtitle
    label: 'LLL:EXT:ns_theme_agency/Resources/Private/Language/locallang_flex.xlf:general.subtitle'
    type: Text
  -
    identifier: appearance_tab
    type: Tab
    label: Appearance
  -
    identifier: space_before_class
    type: Text
    useExistingField: true
  -
    identifier: space_after_class
    type: Text
    useExistingField: true
