name: nitsan/ns-banner
typeName: nitsan_nsbanner
group: t3karma_content_blocks
prefixFields: false
prefixType: vendor
fields:
  -
    identifier: image
    label: 'LLL:EXT:ns_theme_agency/Resources/Private/Language/locallang_flex.xlf:general.bgimage'
    type: File
    allowed:
      - jpg
      - png
      - svg
      - jpeg
      - gif
    minitems: 1
    maxitems: 1
  -
    identifier: title
    label: 'LLL:EXT:ns_theme_agency/Resources/Private/Language/locallang_flex.xlf:general.title'
    type: Text
    required: true
  -
    identifier: subtitle
    label: 'LLL:EXT:ns_theme_agency/Resources/Private/Language/locallang_flex.xlf:general.subtitle'
    type: Text
  -
    identifier: btntext
    label: 'LLL:EXT:ns_theme_agency/Resources/Private/Language/locallang_flex.xlf:general.btntext'
    type: Text
  -
    identifier: scrollid
    label: 'LLL:EXT:ns_theme_agency/Resources/Private/Language/locallang_flex.xlf:general.scrollid'
    type: Text
  -
    identifier: appearance_tab
    type: Tab
    label: Appearance
  -
    identifier: space_before_class
    type: Text
    useExistingField: true
  -
    identifier: space_after_class
    type: Text
    useExistingField: true
